[project]
name = "backtest"
version = "0.1.0"
description = "Backtesting framework for algorithmic trading strategies"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "backtesting>=0.6.1",
    "matplotlib>=3.10.0",
    "pandas>=2.2.3",
    "yfinance>=0.2.52",
]
